# Generated by Django 5.0 on 2023-12-22 18:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("page", "0001_create_model_page_post_statistic"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "date_updated",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "subject",
                    models.CharField(max_length=255, verbose_name="Тема уведомления"),
                ),
                ("message", models.TextField(verbose_name="Сообщение")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Уведомление",
                "verbose_name_plural": "Уведомлении",
                "ordering": ["user", "subject"],
            },
        ),
        migrations.CreateModel(
            name="PageStatistic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "date_updated",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "post_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Количество постов"
                    ),
                ),
                (
                    "subscriber_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Количество подписчиков"
                    ),
                ),
                (
                    "like_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Количество лайков"
                    ),
                ),
                (
                    "page",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statistics",
                        to="page.page",
                    ),
                ),
            ],
            options={
                "verbose_name": "Статистика страницы",
                "verbose_name_plural": "Статистика страниц",
                "ordering": ["page", "post_count", "subscriber_count"],
            },
        ),
    ]
